import{S as b,i as w,a as v}from"./assets/vendor-c145bea9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function d(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerpolicy&&(a.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?a.credentials="include":t.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(t){if(t.ep)return;t.ep=!0;const a=d(t);fetch(t.href,a)}})();let i=1,f="",y=40,l=0;const S=document.querySelector(".search-form"),h=new URL("https://pixabay.com/api/"),p=document.querySelector(".gallery"),c=document.querySelector(".loader"),o=document.querySelector(".load-more-btn"),n=document.querySelector(".end-text"),q=new b(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});async function g(){const r={key:"41612762-752dc9341b43071862b7b3b8c",q:f,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:y};h.search=new URLSearchParams(r);try{return(await v.get(h)).data}catch{m()}}function L(r,e){const d=e.hits.map(s=>`<li class="img-gallery-item"><a class="gallery-link" href="${s.largeImageURL}"><img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" width="${s.webformatWidth}"></a>
        <div class="info-img">
          <p>Likes<span>${s.likes}</span></p>
          <p>Views<span>${s.views}</span></p>
          <p>Comments<span>${s.comments}</span></p>
          <p>Downloads<span>${s.downloads}</span></p>
        </div>
      </li>`).join("");r.insertAdjacentHTML("beforeend",d),q.refresh()}function $(){return document.querySelector(".img-gallery-item").getBoundingClientRect().height}function k(r){window.scrollBy({top:r,behavior:"smooth"})}S.addEventListener("submit",async r=>{try{r.preventDefault(),i=1,f=r.currentTarget.elements.query.value.trim(),p.innerHTML="",n.classList.add("is-hidden"),c.style.display="block";const e=await g();if(e.totalHits===0)throw o.classList.add("is-hidden"),n.classList.add("is-hidden"),new Error("No images found");l=e.totalHits,L(p,e),o.classList.remove("is-hidden"),n.classList.add("is-hidden"),i>=Math.ceil(l/y)&&(o.classList.add("is-hidden"),n.classList.remove("is-hidden"))}catch{m()}finally{c.style.display="none"}});o.addEventListener("click",async()=>{try{i+=1,c.style.display="block",o.classList.add("is-hidden");const r=await g();L(p,r),alert(`Знайдено результатів ${l}`);const e=$();k(e*2.2),i>=Math.ceil(l/y)?n.classList.remove("is-hidden"):o.classList.remove("is-hidden")}catch{m()}finally{c.style.display="none"}});function m(){return w.error({title:"Error",position:"center",message:"Sorry, there are no images matching your search query. Please try again!"})}
//# sourceMappingURL=commonHelpers.js.map
