import{S as b,i as w,a as v}from"./assets/vendor-c145bea9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function d(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=d(t);fetch(t.href,o)}})();let i=1,f="",y=40,n=0;const S=document.querySelector(".search-form"),h=new URL("https://pixabay.com/api/"),p=document.querySelector(".gallery"),c=document.querySelector(".loader"),a=document.querySelector(".load-more-btn"),l=document.querySelector(".end-text"),q=new b(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});async function g(){const r={key:"41612762-752dc9341b43071862b7b3b8c",q:f,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:y};h.search=new URLSearchParams(r);try{return(await v.get(h)).data}catch{m()}}function L(r,e){const d=e.hits.map(s=>`<li class="img-gallery-item"><a class="gallery-link" href="${s.largeImageURL}"><img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" width="${s.webformatWidth}"></a>
        <div class="info-img">
          <p>Likes<span>${s.likes}</span></p>
          <p>Views<span>${s.views}</span></p>
          <p>Comments<span>${s.comments}</span></p>
          <p>Downloads<span>${s.downloads}</span></p>
        </div>
      </li>`).join("");r.insertAdjacentHTML("beforeend",d),q.refresh()}function k(){return document.querySelector(".img-gallery-item").getBoundingClientRect().height}function $(r){window.scrollBy({top:r,behavior:"smooth"})}S.addEventListener("submit",async r=>{r.preventDefault(),i=1,f=r.currentTarget.elements.query.value.trim(),p.innerHTML="",c.style.display="block",g().then(e=>{if(e.totalHits===0)throw a.classList.add("is-hidden"),l.classList.add("is-hidden"),new Error("No images found");n=e.totalHits,L(p,e),a.classList.remove("is-hidden"),l.classList.add("is-hidden"),i>=Math.ceil(n/y)&&(a.classList.add("is-hidden"),l.classList.remove("is-hidden"))}).catch(e=>m()).finally(()=>{c.style.display="none",console.log("All: "+n)})});a.addEventListener("click",async()=>{try{i+=1,c.style.display="block",g().then(r=>{L(p,r);const e=k();$(e*2.2)}).finally(()=>{c.style.display="none",console.log("All: "+n)}),i>=Math.ceil(n/y)&&(a.classList.add("is-hidden"),l.classList.remove("is-hidden"))}catch{m()}});function m(){return w.error({title:"Error",position:"center",message:"Sorry, there are no images matching your search query. Please try again!"})}
//# sourceMappingURL=commonHelpers.js.map
