import{S as w,i as v,a as S}from"./assets/vendor-c145bea9.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerpolicy&&(o.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?o.credentials="include":r.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();let l=1,p="",c=40,y=0;const g=document.querySelector(".search-form"),h=new URL("https://pixabay.com/api/"),m=document.querySelector(".gallery"),d=document.querySelector(".loader"),a=document.querySelector(".load-more-btn"),i=document.querySelector(".end-text"),q=new w(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});async function L(t,e,n){const s={key:"41612762-752dc9341b43071862b7b3b8c",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:n};h.search=new URLSearchParams(s);try{return(await S.get(h)).data}catch{f()}}function b(t,e){console.log(e),console.log(e.hits),console.log(e.total);const n=e.hits.map(s=>`<li class="img-gallery-item"><a class="gallery-link" href="${s.largeImageURL}"><img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" width="${s.webformatWidth}"></a>
        <div class="info-img">
          <p>Likes<span>${s.likes}</span></p>
          <p>Views<span>${s.views}</span></p>
          <p>Comments<span>${s.comments}</span></p>
          <p>Downloads<span>${s.downloads}</span></p>
        </div>
      </li>`).join("");t.insertAdjacentHTML("beforeend",n),q.refresh()}function k(){return document.querySelector(".img-gallery-item").getBoundingClientRect().height}function $(t){window.scrollBy({top:t,behavior:"smooth"})}g.addEventListener("submit",async t=>{try{t.preventDefault(),p=t.currentTarget.elements.query.value.trim(),m.innerHTML="",i.classList.add("is-hidden"),d.style.display="block";const e=await L(p,l=1,c);if(e.totalHits===0)throw a.classList.add("is-hidden"),i.classList.add("is-hidden"),new Error("No images found");y=e.totalHits,b(m,e),a.classList.remove("is-hidden"),i.classList.add("is-hidden"),l>=Math.ceil(y/c)&&(a.classList.add("is-hidden"),i.classList.remove("is-hidden"))}catch{f()}finally{d.style.display="none"}});g.addEventListener("mousedown",function(t){t.target.classList.value==="form-control"&&t.target.value!==""&&(t.target.value="")});a.addEventListener("click",async()=>{try{l+=1,d.style.display="block",a.classList.add("is-hidden");const t=await L(p,l,c);b(m,t);const e=k();$(e*2.2),l>=Math.ceil(y/c)?i.classList.remove("is-hidden"):a.classList.remove("is-hidden")}catch{f()}finally{d.style.display="none"}});function f(){return v.error({title:"Error",position:"center",message:"Sorry, there are no images matching your search query. Please try again!"})}
//# sourceMappingURL=commonHelpers.js.map
